name: Actualizar Tracker # Reactivando cron

on:
  schedule:
    - cron: '*/5 * * * *' # Ejecutar cada 5 minutos
  workflow_dispatch: # Permite ejecutarlo manualmente pulsando un botón

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar librerías
        run: pip install curl_cffi

      - name: Ejecutar Tracker
        run: python tracker.py

      - name: Guardar cambios (Commit)
        run: |
          git config --global user.name 'Tracker Bot'
          git config --global user.email 'bot@noreply.github.com'
          git add tracker_youtube.csv
          git commit -m "Actualizacion automatica de datos" || exit 0
          git push
